import { MenuItem, MenuPoll, InventoryItem, DailyStats } from './canteenTypes';

export const mockMenuItems: MenuItem[] = [
  // Breakfast
  {
    id: 'M001',
    name: 'Idli Sambar',
    category: 'Breakfast',
    price: 40,
    available: true,
    preparationTime: 15,
    isVeg: true,
    description: 'Soft steamed rice cakes with lentil curry',
    ingredients: ['Rice', 'Urad Dal', 'Sambar', 'Chutney'],
  },
  {
    id: 'M002',
    name: 'Masala Dosa',
    category: 'Breakfast',
    price: 50,
    available: true,
    preparationTime: 20,
    isVeg: true,
    description: 'Crispy rice crepe with spiced potato filling',
    ingredients: ['Rice', 'Potato', 'Onion', 'Spices'],
  },
  {
    id: 'M003',
    name: 'Poha',
    category: 'Breakfast',
    price: 35,
    available: true,
    preparationTime: 10,
    isVeg: true,
    description: 'Flattened rice with peanuts and curry leaves',
  },
  {
    id: 'M004',
    name: 'Bread Omelette',
    category: 'Breakfast',
    price: 45,
    available: false,
    preparationTime: 10,
    isVeg: false,
    description: 'Fluffy omelette with bread slices',
  },
  
  // Lunch
  {
    id: 'M005',
    name: 'Veg Thali',
    category: 'Lunch',
    price: 80,
    available: true,
    preparationTime: 25,
    isVeg: true,
    description: 'Complete meal with rice, roti, dal, sabzi, and curd',
    ingredients: ['Rice', 'Wheat', 'Dal', 'Vegetables', 'Curd'],
  },
  {
    id: 'M006',
    name: 'Chicken Biryani',
    category: 'Lunch',
    price: 120,
    available: true,
    preparationTime: 30,
    isVeg: false,
    description: 'Aromatic basmati rice with tender chicken pieces',
  },
  {
    id: 'M007',
    name: 'Paneer Butter Masala',
    category: 'Lunch',
    price: 90,
    available: true,
    preparationTime: 20,
    isVeg: true,
    description: 'Cottage cheese in rich creamy tomato gravy',
  },
  {
    id: 'M008',
    name: 'Dal Fry with Rice',
    category: 'Lunch',
    price: 60,
    available: true,
    preparationTime: 15,
    isVeg: true,
    description: 'Tempered lentils with steamed rice',
  },
  
  // Dinner
  {
    id: 'M009',
    name: 'Chapati with Curry',
    category: 'Dinner',
    price: 70,
    available: true,
    preparationTime: 20,
    isVeg: true,
    description: 'Whole wheat flatbread with mixed vegetable curry',
  },
  {
    id: 'M010',
    name: 'Fried Rice',
    category: 'Dinner',
    price: 75,
    available: true,
    preparationTime: 15,
    isVeg: true,
    description: 'Stir-fried rice with vegetables and sauces',
  },
  
  // Snacks
  {
    id: 'M011',
    name: 'Samosa',
    category: 'Snacks',
    price: 20,
    available: true,
    preparationTime: 5,
    isVeg: true,
    description: 'Crispy fried pastry with spiced potato filling',
  },
  {
    id: 'M012',
    name: 'Vada Pav',
    category: 'Snacks',
    price: 25,
    available: true,
    preparationTime: 5,
    isVeg: true,
    description: 'Spiced potato fritter in a bread bun',
  },
  {
    id: 'M013',
    name: 'Pakora',
    category: 'Snacks',
    price: 30,
    available: true,
    preparationTime: 10,
    isVeg: true,
    description: 'Mixed vegetable fritters',
  },
  
  // Beverages
  {
    id: 'M014',
    name: 'Chai',
    category: 'Beverages',
    price: 15,
    available: true,
    preparationTime: 5,
    isVeg: true,
    description: 'Indian spiced milk tea',
  },
  {
    id: 'M015',
    name: 'Coffee',
    category: 'Beverages',
    price: 20,
    available: true,
    preparationTime: 5,
    isVeg: true,
    description: 'Hot filter coffee',
  },
  {
    id: 'M016',
    name: 'Lassi',
    category: 'Beverages',
    price: 30,
    available: true,
    preparationTime: 5,
    isVeg: true,
    description: 'Refreshing yogurt-based drink',
  },
];

export const mockMenuPolls: MenuPoll[] = [
  {
    id: 'P001',
    pollId: 'POLL2024001',
    title: "Tonight's Dinner Menu",
    mealType: 'Dinner',
    date: '2024-03-14',
    status: 'Active',
    totalVotes: 156,
    createdAt: '2024-03-14T10:00:00',
    closesAt: '2024-03-14T16:00:00',
    options: [
      {
        id: 'OPT001',
        name: 'North Indian Thali',
        description: 'Roti, Dal Makhani, Paneer Curry, Rice, Raita',
        items: ['Roti (4 pcs)', 'Dal Makhani', 'Paneer Curry', 'Jeera Rice', 'Raita'],
        votes: 89,
        percentage: 57,
        isVeg: true,
      },
      {
        id: 'OPT002',
        name: 'South Indian Special',
        description: 'Idli, Dosa, Sambar, Coconut Chutney',
        items: ['Idli (3 pcs)', 'Masala Dosa', 'Sambar', 'Coconut Chutney', 'Filter Coffee'],
        votes: 45,
        percentage: 29,
        isVeg: true,
      },
      {
        id: 'OPT003',
        name: 'Chicken Biryani Combo',
        description: 'Chicken Biryani with Raita and Salad',
        items: ['Chicken Biryani', 'Raita', 'Mixed Salad', 'Pickle'],
        votes: 22,
        percentage: 14,
        isVeg: false,
      },
    ],
  },
  {
    id: 'P002',
    pollId: 'POLL2024002',
    title: "Tomorrow's Lunch Menu",
    mealType: 'Lunch',
    date: '2024-03-15',
    status: 'Scheduled',
    totalVotes: 0,
    createdAt: '2024-03-14T11:00:00',
    closesAt: '2024-03-15T09:00:00',
    options: [
      {
        id: 'OPT004',
        name: 'Veg Thali',
        description: 'Complete vegetarian meal',
        items: ['Rice', 'Roti', 'Dal', 'Mixed Veg Curry', 'Curd', 'Pickle'],
        votes: 0,
        percentage: 0,
        isVeg: true,
      },
      {
        id: 'OPT005',
        name: 'Chole Bhature',
        description: 'Spiced chickpeas with fried bread',
        items: ['Chole', 'Bhature (2 pcs)', 'Onion Salad', 'Pickle', 'Sweet'],
        votes: 0,
        percentage: 0,
        isVeg: true,
      },
      {
        id: 'OPT006',
        name: 'Pulao with Raita',
        description: 'Vegetable pulao with yogurt',
        items: ['Veg Pulao', 'Raita', 'Papad', 'Salad'],
        votes: 0,
        percentage: 0,
        isVeg: true,
      },
    ],
  },
  {
    id: 'P003',
    pollId: 'POLL2024003',
    title: "Yesterday's Dinner Menu",
    mealType: 'Dinner',
    date: '2024-03-13',
    status: 'Closed',
    totalVotes: 203,
    createdAt: '2024-03-13T10:00:00',
    closesAt: '2024-03-13T16:00:00',
    winningOption: 'Paneer Fried Rice Combo',
    options: [
      {
        id: 'OPT007',
        name: 'Paneer Fried Rice Combo',
        description: 'Chinese style fried rice with paneer',
        items: ['Paneer Fried Rice', 'Manchurian', 'Spring Roll', 'Soup'],
        votes: 125,
        percentage: 62,
        isVeg: true,
      },
      {
        id: 'OPT008',
        name: 'Rajma Chawal',
        description: 'Kidney beans curry with rice',
        items: ['Rajma', 'Steamed Rice', 'Salad', 'Papad'],
        votes: 52,
        percentage: 25,
        isVeg: true,
      },
      {
        id: 'OPT009',
        name: 'Mix Veg with Roti',
        description: 'Mixed vegetable curry with flatbread',
        items: ['Mix Veg Curry', 'Roti (4 pcs)', 'Dal', 'Rice'],
        votes: 26,
        percentage: 13,
        isVeg: true,
      },
    ],
  },
];

export const mockInventory: InventoryItem[] = [
  {
    id: 'INV001',
    name: 'Basmati Rice',
    category: 'Grains',
    quantity: 150,
    unit: 'kg',
    minimumStock: 50,
    lastUpdated: '2024-03-14T10:00:00',
    status: 'In Stock',
  },
  {
    id: 'INV002',
    name: 'Whole Wheat Flour',
    category: 'Grains',
    quantity: 80,
    unit: 'kg',
    minimumStock: 40,
    lastUpdated: '2024-03-14T10:00:00',
    status: 'In Stock',
  },
  {
    id: 'INV003',
    name: 'Potatoes',
    category: 'Vegetables',
    quantity: 25,
    unit: 'kg',
    minimumStock: 30,
    lastUpdated: '2024-03-13T15:00:00',
    status: 'Low Stock',
  },
  {
    id: 'INV004',
    name: 'Tomatoes',
    category: 'Vegetables',
    quantity: 40,
    unit: 'kg',
    minimumStock: 20,
    lastUpdated: '2024-03-14T09:00:00',
    status: 'In Stock',
    expiryDate: '2024-03-20',
  },
  {
    id: 'INV005',
    name: 'Onions',
    category: 'Vegetables',
    quantity: 35,
    unit: 'kg',
    minimumStock: 25,
    lastUpdated: '2024-03-14T09:00:00',
    status: 'In Stock',
  },
  {
    id: 'INV006',
    name: 'Milk',
    category: 'Dairy',
    quantity: 5,
    unit: 'liters',
    minimumStock: 20,
    lastUpdated: '2024-03-14T08:00:00',
    expiryDate: '2024-03-16',
    status: 'Out of Stock',
  },
  {
    id: 'INV007',
    name: 'Paneer',
    category: 'Dairy',
    quantity: 8,
    unit: 'kg',
    minimumStock: 5,
    lastUpdated: '2024-03-14T08:00:00',
    expiryDate: '2024-03-17',
    status: 'In Stock',
  },
  {
    id: 'INV008',
    name: 'Toor Dal',
    category: 'Grains',
    quantity: 45,
    unit: 'kg',
    minimumStock: 20,
    lastUpdated: '2024-03-14T10:00:00',
    status: 'In Stock',
  },
  {
    id: 'INV009',
    name: 'Cooking Oil',
    category: 'Others',
    quantity: 12,
    unit: 'liters',
    minimumStock: 15,
    lastUpdated: '2024-03-13T14:00:00',
    status: 'Low Stock',
  },
  {
    id: 'INV010',
    name: 'Turmeric Powder',
    category: 'Spices',
    quantity: 3,
    unit: 'kg',
    minimumStock: 2,
    lastUpdated: '2024-03-14T10:00:00',
    status: 'In Stock',
  },
];

export const mockDailyStats: DailyStats = {
  totalPolls: 8,
  activePolls: 1,
  totalVotes: 156,
  participationRate: 78,
  popularChoices: [
    { name: 'North Indian Thali', votes: 89 },
    { name: 'South Indian Special', votes: 45 },
    { name: 'Paneer Fried Rice Combo', votes: 125 },
    { name: 'Veg Thali', votes: 98 },
  ],
  upcomingMeals: [
    { meal: "Tonight's Dinner", status: 'Active', votes: 156 },
    { meal: "Tomorrow's Lunch", status: 'Scheduled', votes: 0 },
    { meal: "Tomorrow's Dinner", status: 'Scheduled', votes: 0 },
  ],
};